" Use XDG data directory
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo

" General settings
autocmd! BufWritePost $MYVIMRC source %  " Automatically source vimrc when it is saved
syntax enable                            " Enable syntax highlighting
set term=xterm                           " Required for mouse when running vim in alacritty
set mouse=a                              " Enable the mouse
set hidden                               " Key multiple buffers open
set encoding=utf-8                       " Use utf-8
set fileencoding=utf-8                   " Use utf-8 when saving file
set nobackup                             " Don't backup edited files
set nowritebackup                        " Don't backup edited files
set clipboard=unnamedplus                " Copy and paste between vim and the rest of the system

" Line numbers
set number             " Display current line number
set relativenumber     " Display relative line numbers from current line

" Tab settings
set tabstop=4      " Tabs are 4 chars wide
set shiftwidth=4   " Indent at 4 chars
set smarttab       " Let tab figure out 2 vs 4 tabs
set expandtab      " Convert tabs to spaces
set smartindent    " Let vim figure out indenting
set autoindent     " Automattically indent

" GUI controls
set guioptions-=m  " Remove menu bar
set guioptions-=T  " Remove toolbar
set guioptions-=r  " Remove right-hand scrollbar
set guioptions-=L  " Remove left-hand scrollbar
set guioptions-=b  " Remove bottle scrollbar
set guioptions+=c  " Use console dialogs instead of popup dialogs for simple choices
set guioptions+=a  " Enable autoselect into "*: VISUAL mode selection is automatically yanked

" Colors
set cursorline                                   " Highlight the current line
set t_Co=256                                     " Use 256 colors
set background=dark                              " Dark background
autocmd vimenter * ++nested colorscheme gruvbox  " Use gruvbox color scheme

" Key maps
" backup
let g:mapleader = "\<Space>"        " Set leader key to space bar

" Copy and paste like a terminal
map <silent> <S-Insert> "*p
imap <silent> <S-Insert> <Esc>"*pa
map <silent> <C-V> "+p
imap <silent> <C-V> <Esc>"+pa
map <silent> <C-C> "+y
imap <silent> <C-C> <Esc>"+y

" Use Ctrl hjkl to move between windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Use Alt hjkl to resize windows
" Only works in neovim
"nnoremap <M-j> :resize -2<CR>
"nnoremap <M-k> :resize +2<CR>
"nnoremap <M-h> :vertical resize -2<CR>
"nnoremap <M-l> :vertical resize +2<CR>

